image:
  name: andymeneely/swen331fuzzer # don't change this
  entrypoint: [""]  # don't change this
before_script:
  # don't change these either
  - chown -R mysql:mysql /var/lib/mysql /var/run/mysqld
  - echo '[+] Starting mysql...'
  - service mysql start
  - echo '[+] Starting apache'
  - service apache2 start
  - python3 -m pip install -q -r requirements.txt
fuzzrunner:
  script:
    # here is where you can write your commands to run your fuzzer or any custom setup commands
    # - echo "hello class"
    # need some example files for vectors and words? These are on the image
    # - cat /words.txt
    # - cat /vectors.txt
    # - cat /badchars.txt
    # An example fuzzer command. Note the url is DIFFERENT than XAMPP example (no /dvwa).
    # Remove whatever you need to.
    - echo "Starting Discover Command"
    - echo "Fuzzing localhost with DVWA authentication"
    - python3 fuzzer/fuzz.py discover http://localhost/ --custom-auth=dvwa --common-words="common-words.txt" --extensions="common-extensions.txt"
    # - echo "Fuzzing localhost with default extensions and no login"
    # - python3 fuzzer/fuzz.py discover http://localhost/ --common-words=common-words.txt
    - echo "Fuzzing /fuzzer-tests"
    - python3 fuzzer/fuzz.py discover http://127.0.0.1/fuzzer-tests --common-words="common-words.txt" --extensions="common-extensions.txt"
    - echo "Done Discovering!"
    - echo "Starting Test Command"
    - python3 fuzzer/fuzz.py test http://localhost/ --custom-auth=dvwa --common-words="common-words.txt" --extensions="common-extensions.txt --vectors=vectors.txt --sensitive=sensitive.txt"
    - echo "Done Testing!"
    - echo "Finished fuzzing!"
  stage: test
