image:
  name: andymeneely/swen331fuzzer # don't change this
  entrypoint: [""]  # don't change this
before_script:
  # don't change these either
  - chown -R mysql:mysql /var/lib/mysql /var/run/mysqld
  - echo '[+] Starting mysql...'
  - service mysql start
  - echo '[+] Starting apache'
  - service apache2 start
  - python3 -m pip install -q -r requirements.txt
fuzzrunner:
  script:
    - echo "Starting Discover Command"
    - echo "Fuzzing localhost with DVWA authentication"
    - python3 fuzzer/fuzz.py discover http://localhost/ --custom-auth=dvwa --common-words="common-words.txt" --extensions="common-extensions.txt"
    - echo "Fuzzing /fuzzer-tests"
    - python3 fuzzer/fuzz.py discover http://127.0.0.1/fuzzer-tests --common-words="common-words.txt" --extensions="common-extensions.txt"
    - echo "Done Discovering!"
    - echo "Starting Test Command"
    - echo "Running test with specified sanitized chars"
    - python3 fuzzer/fuzz.py test http://localhost/ --custom-auth=dvwa --common-words=common-words.txt --extensions=common-extensions.txt --vectors=vectors.txt --sensitive=sensitive.txt --sanitized-chars=sanitized-chars.txt
    - echo "Running test with default sanitized chars"
    - python3 fuzzer/fuzz.py test http://localhost/ --custom-auth=dvwa --common-words=common-words.txt --extensions=common-extensions.txt --vectors=vectors.txt --sensitive=sensitive.txt
    - echo "Running on fuzzer-tests with specified sanitized chars"
    - python3 fuzzer/fuzz.py test http://localhost/fuzzer-tests --custom-auth=dvwa --common-words=common-words.txt --extensions=common-extensions.txt --vectors=vectors.txt --sensitive=sensitive.txt --sanitized-chars=sanitized-chars.txt
    - echo "Done Testing!"
    - echo "Finished fuzzing!"
  stage: test
